name: kafe
description: "Kafe adalah sebuah aplikasi pencarian coffee shop di Kota Denpasar."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  page_transition: ^2.1.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  flutter_map_animations: ^0.7.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 900

  assets:
    - assets/images/
    - assets/fonts/
    - .env